const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 3000;
const VID = path.join(__dirname, 'uploads/videos');
const SUB = path.join(__dirname, 'uploads/subs');
const THB = path.join(__dirname, 'uploads/thumbnails');
const DB = path.join(__dirname, 'movies.json');

[path.join(__dirname,'uploads'), VID, SUB, THB].forEach(function(d) {
  if (!fs.existsSync(d)) fs.mkdirSync(d, {recursive: true});
  });

  function readDB() {
    if (!fs.existsSync(DB)) return {movies: []};
      return JSON.parse(fs.readFileSync(DB, 'utf8'));
      }

      function writeDB(data) {
        fs.writeFileSync(DB, JSON.stringify(data, null, 2));
        }

        var MIME = {
          '.html': 'text/html;charset=utf-8',
            '.css': 'text/css',
              '.js': 'application/javascript',
                '.json': 'application/json',
                  '.mp4': 'video/mp4',
                    '.webm': 'video/webm',
                      '.mkv': 'video/x-matroska',
                        '.vtt': 'text/vtt;charset=utf-8',
                          '.srt': 'text/plain',
                            '.jpg': 'image/jpeg',
                              '.jpeg': 'image/jpeg',
                                '.png': 'image/png'
                                };

                                function srt2vtt(s) {
                                  return 'WEBVTT\n\n' + s
                                      .replace(/\r\n/g, '\n')
                                          .replace(/\r/g, '\n')
                                              .replace(/(\d{2}:\d{2}:\d{2}),(\d{3})/g, '$1.$2')
                                                  .trim();
                                                  }

                                                  function parseMultipart(req, cb) {
                                                    var body = Buffer.alloc(0);
                                                      req.on('data', function(chunk) { body = Buffer.concat([body, chunk]); });
                                                        req.on('end', function() {
                                                            var ct = req.headers['content-type'] || '';
                                                                var bm = ct.match(/boundary=(.+)$/);
                                                                    if (!bm) return cb(new Error('no boundary'));
                                                                        var bd = '--' + bm[1];
                                                                            var buf = Buffer.from('\r\n' + bd);
                                                                                var sf = bd.length + 2;
                                                                                    var parts = [];
                                                                                        var fields = {};
                                                                                            var files = {};
                                                                                                while (true) {
                                                                                                      var i = body.indexOf(buf, sf - 2);
                                                                                                            if (i === -1) break;
                                                                                                                  parts.push(body.slice(sf, i));
                                                                                                                        sf = i + buf.length + 2;
                                                                                                                            }
                                                                                                                                parts.forEach(function(p) {
                                                                                                                                      var he = p.indexOf('\r\n\r\n');
                                                                                                                                            if (he === -1) return;
                                                                                                                                                  var hs = p.slice(0, he).toString();
                                                                                                                                                        var data = p.slice(he + 4);
                                                                                                                                                              var nm = (hs.match(/name="([^"]+)"/) || [])[1];
                                                                                                                                                                    var fn = (hs.match(/filename="([^"]+)"/) || [])[1];
                                                                                                                                                                          if (!nm) return;
                                                                                                                                                                                if (fn) {
                                                                                                                                                                                        files[nm] = {filename: fn, data: data};
                                                                                                                                                                                              } else {
                                                                                                                                                                                                      fields[nm] = data.toString().trim();
                                                                                                                                                                                                            }
                                                                                                                                                                                                                });
                                                                                                                                                                                                                    cb(null, fields, files);
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                      var server = http.createServer(function(req, res) {
                                                                                                                                                                                                                        var u = new URL(req.url, 'http://localhost:' + PORT);
                                                                                                                                                                                                                          var p = u.pathname;
                                                                                                                                                                                                                            var m = req.method;

                                                                                                                                                                                                                              res.setHeader('Access-Control-Allow-Origin', '*');
                                                                                                                                                                                                                                res.setHeader('Access-Control-Allow-Methods', 'GET,POST,DELETE,OPTIONS');

                                                                                                                                                                                                                                  if (m === 'OPTIONS') { res.writeHead(204); return res.end(); }

                                                                                                                                                                                                                                    if (p === '/api/movies' && m === 'GET') {
                                                                                                                                                                                                                                        var db = readDB();
                                                                                                                                                                                                                                            res.writeHead(200, {'Content-Type': 'application/json'});
                                                                                                                                                                                                                                                return res.end(JSON.stringify(db.movies));
                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                    if (p === '/api/upload' && m === 'POST') {
                                                                                                                                                                                                                                                        parseMultipart(req, function(err, fields, files) {
                                                                                                                                                                                                                                                              if (err) {
                                                                                                                                                                                                                                                                      res.writeHead(400, {'Content-Type': 'application/json'});
                                                                                                                                                                                                                                                                              return res.end(JSON.stringify({error: err.message}));
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                          var vf = files.video;
                                                                                                                                                                                                                                                                                                var sf = files.subtitle;
                                                                                                                                                                                                                                                                                                      if (!vf) {
                                                                                                                                                                                                                                                                                                              res.writeHead(400, {'Content-Type': 'application/json'});
                                                                                                                                                                                                                                                                                                                      return res.end(JSON.stringify({error: 'Видео файл байхгүй'}));
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                  var id = Date.now().toString();
                                                                                                                                                                                                                                                                                                                                        var ve = path.extname(vf.filename).toLowerCase();
                                                                                                                                                                                                                                                                                                                                              var vn = id + ve;
                                                                                                                                                                                                                                                                                                                                                    fs.writeFileSync(path.join(VID, vn), vf.data);
                                                                                                                                                                                                                                                                                                                                                          var sn = null;
                                                                                                                                                                                                                                                                                                                                                                if (sf && sf.filename) {
                                                                                                                                                                                                                                                                                                                                                                        sn = id + '.vtt';
                                                                                                                                                                                                                                                                                                                                                                                var se = path.extname(sf.filename).toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                        var sc = se === '.srt' ? srt2vtt(sf.data.toString('utf8')) : sf.data;
                                                                                                                                                                                                                                                                                                                                                                                                fs.writeFileSync(path.join(SUB, sn), sc);
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                            var db2 = readDB();
                                                                                                                                                                                                                                                                                                                                                                                                                  var mv = {
                                                                                                                                                                                                                                                                                                                                                                                                                          id: id,
                                                                                                                                                                                                                                                                                                                                                                                                                                  title: fields.title || vf.filename,
                                                                                                                                                                                                                                                                                                                                                                                                                                          year: fields.year || new Date().getFullYear(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                  genre: fields.genre || 'Бусад',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          description: fields.description || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  videoFile: vn,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subFile: sn,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  thumbnail: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          uploadedAt: new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      db2.movies.push(mv);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            writeDB(db2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.writeHead(200, {'Content-Type': 'application/json'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.end(JSON.stringify({success: true, movie: mv}));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (p.startsWith('/api/movies/') && m === 'DELETE') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var id2 = p.split('/')[3];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var db3 = readDB();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var mv2 = db3.movies.find(function(x) { return x.id === id2; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (mv2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try { fs.unlinkSync(path.join(VID, mv2.videoFile)); } catch(e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (mv2.subFile) try { fs.unlinkSync(path.join(SUB, mv2.subFile)); } catch(e) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      db3.movies = db3.movies.filter(function(x) { return x.id !== id2; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            writeDB(db3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.writeHead(200, {'Content-Type': 'application/json'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.end(JSON.stringify({success: true}));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (p.startsWith('/uploads/videos/')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var fn = p.replace('/uploads/videos/', '');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var fp = path.join(VID, fn);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!fs.existsSync(fp)) { res.writeHead(404); return res.end(); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var st = fs.statSync(fp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var tot = st.size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var rng = req.headers.range;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var mt = MIME[path.extname(fn).toLowerCase()] || 'video/mp4';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (rng) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var parts = rng.replace(/bytes=/, '').split('-');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var start = parseInt(parts[0], 10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              var end = parts[1] ? parseInt(parts[1], 10) : Math.min(start + 1048575, tot - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.writeHead(206, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Range': 'bytes ' + start + '-' + end + '/' + tot,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Accept-Ranges': 'bytes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Length': end - start + 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Type': mt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fs.createReadStream(fp, {start: start, end: end}).pipe(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.writeHead(200, {'Content-Length': tot, 'Content-Type': mt, 'Accept-Ranges': 'bytes'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fs.createReadStream(fp).pipe(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (p.startsWith('/uploads/subs/')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var fp2 = path.join(SUB, p.replace('/uploads/subs/', ''));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!fs.existsSync(fp2)) { res.writeHead(404); return res.end(); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.writeHead(200, {'Content-Type': 'text/vtt;charset=utf-8'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return fs.createReadStream(fp2).pipe(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (p.startsWith('/uploads/thumbnails/')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var fp3 = path.join(THB, p.replace('/uploads/thumbnails/', ''));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!fs.existsSync(fp3)) { res.writeHead(404); return res.end(); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.writeHead(200, {'Content-Type': 'image/jpeg'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return fs.createReadStream(fp3).pipe(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var fp4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (p === '/' || p === '/index.html') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fp4 = path.join(__dirname, 'public/index.html');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (p === '/admin' || p === '/admin.html') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fp4 = path.join(__dirname, 'public/admin.html');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fp4 = path.join(__dirname, 'public', p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (fs.existsSync(fp4) && fs.statSync(fp4).isFile()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.writeHead(200, {'Content-Type': MIME[path.extname(fp4).toLowerCase()] || 'text/plain'});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return fs.createReadStream(fp4).pipe(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.writeHead(404);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.end('404');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        server.listen(PORT, function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('MNFLIX running on port ' + PORT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          